server:
  servlet:
    context-path: /
  port: 9000
spring:
  application:
    name: micr-pay
  redis:
    host: localhost
    port: 6379
dubbo:
  scan:
    base-packages: com.lwm.pay
  registry:
    address: zookeeper://localhost:2181
  consumer:
    timeout: 40000
    retries: 0
    check: false

