spring:
  application:
    name: micr-task

dubbo:
  scan:
    base-packages: com.lwm.task
  registry:
    address: zookeeper://localhost:2181
  consumer:
    timeout: 40000
    retries: 0
    check: false
