server:
  port: 8000
  servlet:
    context-path: /
spring:
  application:
    name: micr-web
  redis:
    host: localhost
    port: 6379

dubbo:
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.lwm.web
  consumer:
    timeout: 40000
    retries: 0
    check: false

#密钥
jwt-secretkey: 37de4f4e7c324c7296aed4322fd0804d
